packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  vite-plugin-dts: ^4.5.3
  vue: ^3.5.13
  vue-router: ^4.5.0
  perfect-debounce: ^1.0.0
  shiki: ^3.2.1
  splitpanes: ^3.2.0
  vue-virtual-scroller: 2.0.0-beta.8
  '@vitejs/plugin-vue': ^5.2.3
  '@iconify/json': ^2.2.321
  '@types/node': ^22.13.14
  '@unocss/reset': ^66.0.0
  floating-vue: 5.2.2
  pinia: ^3.0.1
  sass-embedded: ^1.86.0
  unocss: ^66.0.0
  unplugin-auto-import: ^19.1.2
  vite: ^6.2.1
  '@vueuse/core': ^12.8.2
  '@vueuse/integrations': ^12.8.2
  colord: ^2.9.3
  vite-hot-client: ^2.0.4
  mitt: ^3.0.1
  pathe: ^2.0.3
  execa: ^9.5.2
  vite-plugin-inspect: ^0.10.6
  serve: ^14.2.4
  typescript: ^5.8.2
