packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  '@iconify/json': ^2.2.395
  '@types/node': ^24.7.2
  '@unocss/reset': ^66.5.4
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  colord: ^2.9.3
  floating-vue: 5.2.2
  pathe: ^2.0.3
  perfect-debounce: ^2.0.0
  pinia: ^3.0.3
  sass-embedded: ^1.93.2
  serve: ^14.2.5
  shiki: ^3.13.0
  splitpanes: ^4.0.4
  typescript: ^5.9.3
  unocss: ^66.5.4
  unplugin-auto-import: ^20.2.0
  vite: ^7.1.11
  vite-hot-client: ^2.1.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: ^11.3.3
  vue: ^3.5.22
  vue-router: ^4.6.0
  vue-virtual-scroller: 2.0.0-beta.8

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - simple-git-hooks
  - yorkie

onlyBuiltDependencies:
  - electron
  - esbuild
  - vue-demi

shamefullyHoist: true
strictPeerDependencies: false
sideEffectsCache: false
shellEmulator: true
