packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  '@iconify/json': ^2.2.349
  '@types/node': ^22.15.31
  '@unocss/reset': ^66.2.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vueuse/core': ^12.8.2
  '@vueuse/integrations': ^12.8.2
  colord: ^2.9.3
  execa: ^9.6.0
  floating-vue: 5.2.2
  mitt: ^3.0.1
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pinia: ^3.0.3
  sass-embedded: ^1.89.2
  serve: ^14.2.4
  shiki: ^3.6.0
  splitpanes: ^4.0.4
  typescript: ^5.8.3
  unocss: ^66.2.0
  unplugin-auto-import: ^19.3.0
  vite: ^6.2.1
  vite-hot-client: ^2.0.4
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: 0.8.9
  vue: ^3.5.16
  vue-router: ^4.5.1
  vue-virtual-scroller: 2.0.0-beta.8
