packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  '@iconify/json': ^2.2.363
  '@types/node': ^24.1.0
  '@unocss/reset': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': ^13.6.0
  '@vueuse/integrations': ^13.6.0
  colord: ^2.9.3
  execa: ^9.6.0
  floating-vue: 5.2.2
  mitt: ^3.0.1
  pathe: ^2.0.3
  perfect-debounce: ^1.0.0
  pinia: ^3.0.3
  sass-embedded: ^1.89.2
  serve: ^14.2.4
  shiki: ^3.8.1
  splitpanes: ^4.0.4
  typescript: ^5.8.3
  unocss: ^66.3.3
  unplugin-auto-import: ^19.3.0
  vite: ^7.0.6
  vite-hot-client: ^2.1.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: ^11.3.0
  vue: ^3.5.18
  vue-router: ^4.5.1
  vue-virtual-scroller: 2.0.0-beta.8
