packages:
  - packages/*
  - docs
  - packages/playground/**

catalog:
  '@iconify/json': ^2.2.439
  '@types/node': ^24.10.13
  '@unocss/reset': ^66.6.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  colord: ^2.9.3
  floating-vue: 5.2.2
  pathe: ^2.0.3
  perfect-debounce: ^2.1.0
  pinia: ^3.0.4
  sass-embedded: ^1.97.3
  serve: ^14.2.5
  shiki: ^3.22.0
  splitpanes: ^4.0.4
  typescript: ^5.9.3
  unocss: ^66.6.0
  unplugin-auto-import: ^20.3.0
  vite: ^7.1.10
  vite-hot-client: ^2.1.0
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: ^11.3.3
  vue: ^3.5.28
  vue-router: ^4.6.4
  vue-virtual-scroller: 2.0.0-beta.8

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - simple-git-hooks
  - yorkie

onlyBuiltDependencies:
  - electron
  - esbuild
  - vue-demi

shamefullyHoist: true
strictPeerDependencies: false
sideEffectsCache: false
shellEmulator: true
