// https://vitepress.dev/guide/custom-theme
import Theme from 'vitepress/theme'
import { h } from 'vue'
// @ts-expect-error virtual stylesheet generated by UnoCSS
import 'uno.css'
// @ts-expect-error stylesheet handled by VitePress
import './style.css'
// @ts-expect-error virtual stylesheet generated by vitepress-plugin-group-icons
import 'virtual:group-icons.css'

export default {
  extends: Theme,
  Layout: () => {
    return h(Theme.Layout, null, {})
  },
}
