name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        # https://github.com/nitrojs/nitro/pull/3060
        # https://github.com/nodejs/corepack/pull/614
        run: npm i -g --force corepack && corepack enable pnpm

      - name: Setup ni
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Lint
        run: nr lint

      - name: Test
        run: nr test
